name: shell
dependencies:
  js: any
  over_react: ^2.0.0

dependency_overrides:
  shell_events:
    path: ../shell_events

dev_dependencies:
  build_runner: ">=1.6.2 <2.0.0"
  build_test:
  build_web_compilers:
